### ISSUE TITLE
Updated Entries

### ISSUE THREAD

**Issue by jbrayton** [feedbin/feedbin-api#43]
I like Feedbin’s ability to tell when an entry has been updated. Right now Unread does not pick up changes to Feedbin entries. I would like to fix that. I am trying to determine the best way to do so.

It looks like I can call /v2/updated_entries.json to determine what articles have updates. Is there a way to determine what articles have been updated since last time I checked?

**Comment by benubois** [comment]
I think checking `/v2/updated_entries.json` is a great start. 

I do see how it would be possible that an entry could be updated multiple times and Unread would miss changes if it had already retrieved the updates one time.

What about something like a `since` parameter where `since` is an iso8601 date when you last checked the `/v2/updated_entries.json` endpoint?

A request might look like:

```
https://api.feedbin.com/v2/updated_entries.json?since=2020-01-31T14:57:48.471769Z
```

Then the response would be just the ids that were updated since that date:

```json
[2334768066, 2334768065]
```

**Comment by jbrayton** [comment]
Hi Ben. Making the "since" parameter work for that API call would be perfect. Thanks!

**Comment by benubois** [comment]
Done!

**Comment by jbrayton** [comment]
That was quick - thank you!
